import type { Stadium } from '@/types'

export const STADIUMS_DATA: Omit<Stadium, 'id' | 'created_at'>[] = [
  // AL East
  {
    name: 'Fenway Park',
    team: 'Boston Red Sox',
    abbreviation: 'BOS',
    city: 'Boston',
    state: 'MA',
    lat: 42.3467,
    lng: -71.0972,
    capacity: 37755,
    opened: 1912,
    surface: 'Grass',
    league: 'AL',
    division: 'East',
  },
  {
    name: 'Yankee Stadium',
    team: 'New York Yankees',
    abbreviation: 'NYY',
    city: 'Bronx',
    state: 'NY',
    lat: 40.8296,
    lng: -73.9262,
    capacity: 47309,
    opened: 2009,
    surface: 'Grass',
    league: 'AL',
    division: 'East',
  },
  {
    name: 'Camden Yards',
    team: 'Baltimore Orioles',
    abbreviation: 'BAL',
    city: 'Baltimore',
    state: 'MD',
    lat: 39.2838,
    lng: -76.6218,
    capacity: 44970,
    opened: 1992,
    surface: 'Grass',
    league: 'AL',
    division: 'East',
  },
  {
    name: 'Tropicana Field',
    team: 'Tampa Bay Rays',
    abbreviation: 'TB',
    city: 'St. Petersburg',
    state: 'FL',
    lat: 27.7682,
    lng: -82.6534,
    capacity: 25000,
    opened: 1990,
    surface: 'AstroTurf',
    league: 'AL',
    division: 'East',
  },
  {
    name: 'Rogers Centre',
    team: 'Toronto Blue Jays',
    abbreviation: 'TOR',
    city: 'Toronto',
    state: 'ON',
    lat: 43.6414,
    lng: -79.3894,
    capacity: 49286,
    opened: 1989,
    surface: 'AstroTurf',
    league: 'AL',
    division: 'East',
  },
  // AL Central
  {
    name: 'Guaranteed Rate Field',
    team: 'Chicago White Sox',
    abbreviation: 'CWS',
    city: 'Chicago',
    state: 'IL',
    lat: 41.8299,
    lng: -87.6338,
    capacity: 40615,
    opened: 1991,
    surface: 'Grass',
    league: 'AL',
    division: 'Central',
  },
  {
    name: 'Progressive Field',
    team: 'Cleveland Guardians',
    abbreviation: 'CLE',
    city: 'Cleveland',
    state: 'OH',
    lat: 41.4962,
    lng: -81.6852,
    capacity: 34830,
    opened: 1994,
    surface: 'Grass',
    league: 'AL',
    division: 'Central',
  },
  {
    name: 'Comerica Park',
    team: 'Detroit Tigers',
    abbreviation: 'DET',
    city: 'Detroit',
    state: 'MI',
    lat: 42.3390,
    lng: -83.0485,
    capacity: 41083,
    opened: 2000,
    surface: 'Grass',
    league: 'AL',
    division: 'Central',
  },
  {
    name: 'Kauffman Stadium',
    team: 'Kansas City Royals',
    abbreviation: 'KC',
    city: 'Kansas City',
    state: 'MO',
    lat: 39.0517,
    lng: -94.4803,
    capacity: 37903,
    opened: 1973,
    surface: 'Grass',
    league: 'AL',
    division: 'Central',
  },
  {
    name: 'Target Field',
    team: 'Minnesota Twins',
    abbreviation: 'MIN',
    city: 'Minneapolis',
    state: 'MN',
    lat: 44.9817,
    lng: -93.2776,
    capacity: 38544,
    opened: 2010,
    surface: 'Grass',
    league: 'AL',
    division: 'Central',
  },
  // AL West
  {
    name: 'Minute Maid Park',
    team: 'Houston Astros',
    abbreviation: 'HOU',
    city: 'Houston',
    state: 'TX',
    lat: 29.7572,
    lng: -95.3555,
    capacity: 41168,
    opened: 2000,
    surface: 'Grass',
    league: 'AL',
    division: 'West',
  },
  {
    name: 'Angel Stadium',
    team: 'Los Angeles Angels',
    abbreviation: 'LAA',
    city: 'Anaheim',
    state: 'CA',
    lat: 33.8003,
    lng: -117.8827,
    capacity: 45517,
    opened: 1966,
    surface: 'Grass',
    league: 'AL',
    division: 'West',
  },
  {
    name: 'Sutter Health Park',
    team: 'Oakland Athletics',
    abbreviation: 'OAK',
    city: 'Sacramento',
    state: 'CA',
    lat: 38.5802,
    lng: -121.5088,
    capacity: 14014,
    opened: 2000,
    surface: 'Grass',
    league: 'AL',
    division: 'West',
  },
  {
    name: 'T-Mobile Park',
    team: 'Seattle Mariners',
    abbreviation: 'SEA',
    city: 'Seattle',
    state: 'WA',
    lat: 47.5914,
    lng: -122.3325,
    capacity: 47929,
    opened: 1999,
    surface: 'Grass',
    league: 'AL',
    division: 'West',
  },
  {
    name: 'Globe Life Field',
    team: 'Texas Rangers',
    abbreviation: 'TEX',
    city: 'Arlington',
    state: 'TX',
    lat: 32.7473,
    lng: -97.0823,
    capacity: 40518,
    opened: 2020,
    surface: 'Grass',
    league: 'AL',
    division: 'West',
  },
  // NL East
  {
    name: 'Truist Park',
    team: 'Atlanta Braves',
    abbreviation: 'ATL',
    city: 'Cumberland',
    state: 'GA',
    lat: 33.8908,
    lng: -84.4678,
    capacity: 41084,
    opened: 2017,
    surface: 'Grass',
    league: 'NL',
    division: 'East',
  },
  {
    name: 'loanDepot park',
    team: 'Miami Marlins',
    abbreviation: 'MIA',
    city: 'Miami',
    state: 'FL',
    lat: 25.7781,
    lng: -80.2197,
    capacity: 36742,
    opened: 2012,
    surface: 'Grass',
    league: 'NL',
    division: 'East',
  },
  {
    name: 'Citi Field',
    team: 'New York Mets',
    abbreviation: 'NYM',
    city: 'Flushing',
    state: 'NY',
    lat: 40.7571,
    lng: -73.8458,
    capacity: 41922,
    opened: 2009,
    surface: 'Grass',
    league: 'NL',
    division: 'East',
  },
  {
    name: 'Citizens Bank Park',
    team: 'Philadelphia Phillies',
    abbreviation: 'PHI',
    city: 'Philadelphia',
    state: 'PA',
    lat: 39.9061,
    lng: -75.1665,
    capacity: 42901,
    opened: 2004,
    surface: 'Grass',
    league: 'NL',
    division: 'East',
  },
  {
    name: 'Nationals Park',
    team: 'Washington Nationals',
    abbreviation: 'WSH',
    city: 'Washington',
    state: 'DC',
    lat: 38.8730,
    lng: -77.0074,
    capacity: 41313,
    opened: 2008,
    surface: 'Grass',
    league: 'NL',
    division: 'East',
  },
  // NL Central
  {
    name: 'Wrigley Field',
    team: 'Chicago Cubs',
    abbreviation: 'CHC',
    city: 'Chicago',
    state: 'IL',
    lat: 41.9484,
    lng: -87.6553,
    capacity: 41649,
    opened: 1914,
    surface: 'Grass',
    league: 'NL',
    division: 'Central',
  },
  {
    name: 'Great American Ball Park',
    team: 'Cincinnati Reds',
    abbreviation: 'CIN',
    city: 'Cincinnati',
    state: 'OH',
    lat: 39.0979,
    lng: -84.5082,
    capacity: 42319,
    opened: 2003,
    surface: 'Grass',
    league: 'NL',
    division: 'Central',
  },
  {
    name: 'American Family Field',
    team: 'Milwaukee Brewers',
    abbreviation: 'MIL',
    city: 'Milwaukee',
    state: 'WI',
    lat: 43.0280,
    lng: -87.9712,
    capacity: 41900,
    opened: 2001,
    surface: 'Grass',
    league: 'NL',
    division: 'Central',
  },
  {
    name: 'Busch Stadium',
    team: 'St. Louis Cardinals',
    abbreviation: 'STL',
    city: 'St. Louis',
    state: 'MO',
    lat: 38.6226,
    lng: -90.1928,
    capacity: 44494,
    opened: 2006,
    surface: 'Grass',
    league: 'NL',
    division: 'Central',
  },
  {
    name: 'PNC Park',
    team: 'Pittsburgh Pirates',
    abbreviation: 'PIT',
    city: 'Pittsburgh',
    state: 'PA',
    lat: 40.4469,
    lng: -80.0057,
    capacity: 38362,
    opened: 2001,
    surface: 'Grass',
    league: 'NL',
    division: 'Central',
  },
  // NL West
  {
    name: 'Chase Field',
    team: 'Arizona Diamondbacks',
    abbreviation: 'ARI',
    city: 'Phoenix',
    state: 'AZ',
    lat: 33.4453,
    lng: -112.0667,
    capacity: 48519,
    opened: 1998,
    surface: 'Grass',
    league: 'NL',
    division: 'West',
  },
  {
    name: 'Coors Field',
    team: 'Colorado Rockies',
    abbreviation: 'COL',
    city: 'Denver',
    state: 'CO',
    lat: 39.7559,
    lng: -104.9942,
    capacity: 50398,
    opened: 1995,
    surface: 'Grass',
    league: 'NL',
    division: 'West',
  },
  {
    name: 'Dodger Stadium',
    team: 'Los Angeles Dodgers',
    abbreviation: 'LAD',
    city: 'Los Angeles',
    state: 'CA',
    lat: 34.0739,
    lng: -118.2400,
    capacity: 56000,
    opened: 1962,
    surface: 'Grass',
    league: 'NL',
    division: 'West',
  },
  {
    name: 'Petco Park',
    team: 'San Diego Padres',
    abbreviation: 'SD',
    city: 'San Diego',
    state: 'CA',
    lat: 32.7076,
    lng: -117.1570,
    capacity: 40162,
    opened: 2004,
    surface: 'Grass',
    league: 'NL',
    division: 'West',
  },
  {
    name: 'Oracle Park',
    team: 'San Francisco Giants',
    abbreviation: 'SF',
    city: 'San Francisco',
    state: 'CA',
    lat: 37.7786,
    lng: -122.3893,
    capacity: 41915,
    opened: 2000,
    surface: 'Grass',
    league: 'NL',
    division: 'West',
  },
]
